# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 05:07
from __future__ import unicode_literals

import TasksManager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('client_name', models.CharField(max_length=1000, verbose_name='Client name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('time_elapsed', models.IntegerField(blank=True, default=None, null=True, verbose_name='Elapsed time')),
                ('importance', models.IntegerField(verbose_name='Importance')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TasksManager.Project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadedfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=TasksManager.models.user_directory_bath, verbose_name='Files')),
                ('title', models.CharField(max_length=50, verbose_name='File Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('orginal_headers', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=3)),
                ('selected_headers', models.CharField(default='1', max_length=3)),
                ('modified_file', models.FileField(null=True, upload_to=TasksManager.models.user_directory_bathmodified, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone number')),
                ('born_date', models.DateField(blank=True, default=None, null=True, verbose_name='Born date')),
                ('last_connection', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of last connection')),
                ('years_seniority', models.IntegerField(default=0, verbose_name='Seniority')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TasksManager.UserProfile')),
            ],
            bases=('TasksManager.userprofile',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TasksManager.UserProfile')),
                ('specialisation', models.CharField(max_length=50, verbose_name='Specialisation')),
            ],
            bases=('TasksManager.userprofile',),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TasksManager.Developer', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='task',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TasksManager.Developer', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='developer',
            name='supervisor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TasksManager.Supervisor', verbose_name='Supervisor'),
        ),
    ]
