# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 01:58
from __future__ import unicode_literals

import TasksManager.models
import TasksManager.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TasksManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='supervisor_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TasksManager.Supervisor', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='files',
            field=models.FileField(upload_to=TasksManager.models.user_directory_bath, validators=[TasksManager.validators.validate_file_extension], verbose_name='Files'),
        ),
    ]
